export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_FAILURE = 'GET_ALL_CONTACTS_FAILURE';
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const CREATE_NEW_CONTACT_SUCCESS = "CREATE_NEW_CONTACT_SUCCESS";
export const CREATE_NEW_CONTACT_FAILURE = "CREATE_NEW_CONTACT_FAILURE";
export const CANCEL_NEW_CONTACT = "CANCEL_NEW_CONTACT";
export const UPDATE_NEW_CONTACT = "UPDATE_NEW_CONTACT";
export const SELECT_CONTACT = "SELECT_CONTACT";
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS'
export const UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE'
export const CANCEL_UPDATE = 'CANCEL_UPDATE';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE'
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS'
export const UPDATE_CONTACT_SCORE_SUCCESS = 'UPDATE_CONTACT_SCORE_SUCCESS'
export const UPDATE_CONTACT_SCORE_FAILURE = 'UPDATE_CONTACT_SCORE_FAILURE'
export const SET_CONTACT_ERROR = 'SET_CONTACT_ERROR'


export const AUTH = "AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const SET_DEFAULT = 'SET_DEFAULT';
